# Generated by Django 5.2.8 on 2025-12-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Past questions'),
        ),
    ]
