# Generated by Django 5.2.8 on 2025-12-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='no_of_downloads',
        ),
        migrations.RemoveField(
            model_name='course',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year_used',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Past questions')),
                ('year_used', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('no_of_downloads', models.IntegerField(default=0)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='campus.course')),
            ],
        ),
    ]
