# Generated by Django 5.2.8 on 2025-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_course_description_remove_course_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
