# Generated by Django 4.2.11 on 2025-12-20 10:55

import campus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='no_of_downloads',
        ),
        migrations.AddField(
            model_name='material',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', validators=[campus.models.validate_file_extension, campus.models.validate_file_size]),
        ),
    ]
